language: node_js
node_js:
    - "0.10"
before_script:
    - "export DISPLAY=:99.0"
    - npm install bower grunt-cli testem
    - ./node_modules/bower/bin/bower install
    - sh -e /etc/init.d/xvfb start
    - sleep 3
script:
    - "./node_modules/grunt-cli/bin/grunt jshint:src"
    - "./node_modules/testem/testem.js -l Firefox ci"
notifications:
    emails:
        - kkoonn84@gmail.com
    on_success: change
    on_failure: always
